### PR TITLE
Update github actions due to Node 16 deprecation

### PR DESCRIPTION
**Pull request by kamranf**
Update actions per https://github.com/scribd/job-notification/actions/runs/8014559004:
> Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/checkout@v3, slackapi/slack-github-action@v1.23.0. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

**Note**: could not update `gsactions/commit-message-checker@v2` since there is no new release for it to support Node 20 (per https://github.com/GsActions/commit-message-checker).

### CODE REVIEW

**Review by terranisu — APPROVED** [review]
LGTM 📈

**Review by terranisu — CHANGES_REQUESTED** [review]
I think we need to use either `feat` (preferable) or `fix` prefix in one of the commit messages to ensure a new version (`1.3.0` or `1.2.1`) of the action is released. The `chore` doesn't produce releases (See the [job-notification](https://github.com/scribd/job-notification?tab=readme-ov-file#commit-messages) section).

**Comment by kamranf** [comment]
> I think we need to use either `feat` (preferable) or `fix` prefix in one of the commit messages to ensure a new version (`1.3.0` or `1.2.1`) of the action is released. The `chore` doesn't produce releases (See the [job-notification](https://github.com/scribd/job-notification?tab=readme-ov-file#commit-messages) section).

Thanks for catching that @terranisu ! I just renamed the commit messages per your suggestion.

**Review by terranisu — APPROVED** [review]
LGTM 👍🏻

**Review by helenff — APPROVED** [review]
Thank you for the update! 🏅

**Pull request merged**
